### PR TITLE
Fix subsumption direction in logic.md

### PR DESCRIPTION
**Pull request by antong**

### CODE REVIEW

**Comment by antong** [comment]
I may have this completely wrong!

I now found http://www.coli.uni-saarland.de/courses/syntactic-theory-09/slides/tfs.pdf, which on slide 10 includes the exact original language (the opposite of what I tried to changed it to). However, the implementation note (https://github.com/cuelang/cue/blob/master/doc/ref/impl.md) has the definition the way I tried to change it to.

I don't know what to think :-). Or am I just confused by the direction of the square subset symbol (⊑). If A is a subset of B (A ⊆ B), then B subsumes A (A is subsumed by B). I just assumed the square symbol was the same way around, so that F' ⊑ F means that F' is subsumed by F, i.e., F subsumes F'.

**Comment by antong** [comment]
Well, I just googled "subsume ⊑" and the two top hits use the ⊑ symbol in opposite ways in in relation to the term subsume.

**Comment by myitcv** [comment]
I'll let @mpvl comment on whether this is right/wrong here, but will note the following reference https://research.utwente.nl/en/publications/parallel-natural-language-parsing-from-analysis-to-speedup 😃

**Comment by antong** [comment]
Thanks for the link Paul! I read the definition in Marcel's thesis. It is almost identical to the original logic.md with the same possible issue and an additional typo (reference to undefined t'). I looked at the lecture slides I linked to earlier, and I was wrong that that definition is identical to the one in logic.md. The English vs notation issue is the same "A subsumes B vs A ⊑ B", but then the symbolic definition has half the second criterion reversed "P_F(π)=t implies P_F′(π)=t′ and t⊑t′ ", which looks like a clear error as then neither the English or symbolic definitions match. I googled some more, and found a text by Ann Copestake that also includes the definition (https://www.cl.cam.ac.uk/~aac10/papers/appendix.pdf). Ann's version is exactly what I was trying to change logic.md to read like, so maybe I wasn't completely wrong even though admittedly utterly confused :-)

**Comment by mpvl** [comment]
@antong I agree with your intuition of what it _should_ be, but that seems to collide with the convention within the field. Note that in other texts discussing lattices, top and bottom are often inverted.

So if there are any inconsistencies, this is where that stems from.

It makes sense at some point to go over this, pick one notation, and make it consistent across the board.

**Comment by myitcv** [comment]
Hi @antong - thanks for creating this PR, and for the exchange above.

As you may know, CUE recently moved to a new organisation on GitHub: https://github.com/cue-lang/cue/issues/1078. Unfortunately we were unable to transfer this repository to the new organisation, and so pull requests will need to be re-created at https://github.com/cue-lang/cuelang.org.

Apologies for the inconvenience - we look forward to seeing you in CUE's new home. 

Thank you again for contributing to the CUE project!

**Pull request closed without merging**
