### PR TITLE
light copy editing

### PR DESCRIPTION
**Pull request by mbarkhau**

### CODE REVIEW

**Comment by myitcv** [comment]
Sorry for the delay in getting around to this, @mbarkhau. I notice you closed this and #148. Was that intentional? If so, are you happy for me to pick up these changes? Thanks

**Comment by mbarkhau** [comment]
Yes, was intentional. Feel free to pick them up.

**Comment by myitcv** [comment]
Ok thanks.

**Comment by myitcv** [comment]
Very much appreciate you raising the PRs in the first instance.

**Pull request closed without merging**
