### PR TITLE
Fix typo: missing close-quote

### PR DESCRIPTION
**Pull request by virusdave**
typo: "foo -> "foo"

### CODE REVIEW

**Comment by ahpook** [comment]
LGTM - the test failures are due to the build script brokenness fixed in #67

**Comment by myitcv** [comment]
Thanks for the contribution. Please can you rebase this change against `master`?

**Comment by virusdave** [comment]
> Thanks for the contribution. Please can you rebase this change against `master`?

Yup, rebased!

(github makes this more effort than necessary.  gerrit has spoiled me, i guess)

**Comment by myitcv** [comment]
Thanks again for the fix. Apologies that it's taken ages to get round to merging this.

**Pull request merged**
