### PR TITLE
docs/install: Add installation via go install

### PR DESCRIPTION
**Pull request by micnncim**
Added a description on the way to install `cue` binary via `go install`.

### CODE REVIEW

**Comment by myitcv** [comment]
Thanks - we should ensure that this section is consistent with https://github.com/cuelang/cue#download-and-install

Are you happy make those additional changes in this PR?

**Comment by micnncim** [comment]
This doc has an installation via `yay` but the README in `cuelang/cue` doesn't have. Should I keep that way in this doc?

**Comment by myitcv** [comment]
> This doc has an installation via `yay` but the README in `cuelang/cue` doesn't have. Should I keep that way in this doc?

Yes please.

**Comment by micnncim** [comment]
Sorry for being late. I've updated the change following https://github.com/cuelang/cue#download-and-install.

**Review by myitcv — APPROVED** [review]
LGTM - thanks

**Pull request merged**
